# Generated by Django 5.0.6 on 2024-06-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('tienda', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=30)),
                ('apmaterno', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('fecnac', models.DateField()),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.IntegerField()),
                ('genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='landing.genero')),
            ],
        ),
    ]
